### ISSUE TITLE
VoodooPS2 patch/kext problem

### ISSUE THREAD

**Issue by svobluk** [jsassu20/Lenovo-ThinkPad-T450-Mojave#4]
Hello,

I made everything working almost fine, but I have still problem with TrackPoint and backlight keys, they simply do not work for me now. Sadly, I can't find any issue so far. May I politely ask you for any hint where to look? Many thanks!

*I tried to look at VPS2 patch and voodoops2 kext, but I do not see any issue so far.

**Comment by svobluk** [comment]
I have made it work, some of the patches relevant to this were disabled within config.plist.

**Comment by jsassu20** [comment]
Oh yes I'm sorry I apologize I have them disabled on my system because I use a different trackpad and kext than the one that comes installed natively in the T450. I purchased the clickpad from the T440 and I use the ApplePs2SmartTouchPad.kext because of the amount of customization it's able to utilize compared with VoodooPS2controller.kext. I''l be sure to fix that for the next release I'm getting ready to post in a few minutes.
